version: '2'
services:
  php:
    image: yiisoftware/yii-php:8.1-fpm-nginx
    volumes:
      - .:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    depends_on:
      - db
    networks:
      - my-network

  db:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: yii2db
      MYSQL_USER: yii2user
      MYSQL_PASSWORD: yii2password
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - my-network

  vue:
    build:
      context: .
      dockerfile: ./config/frontend/Dockerfile
    ports:
      - '8081:8080'
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - './vuejs:/var/www:delegated'
    networks:
      - my-network

networks:
  my-network:
    driver: bridge


